[[plugins]]
repo = 'Shougo/dein.vim'

# git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hool_add = '''
source ~/.config/nvim/plugins/coc.rc.vim
'''

# nvimインターフェース統合
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

# ファイルエクスプローラー
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git']
hook_add = '''
source ~/.config/nvim/plugins/defx.rc.vim
'''

# defxgitアイコン
[[plugins]]
repo = 'kristijanhusak/defx-git'
hook_add = '''
source ~/.config/nvim/plugins/defx-git.rc.vim
'''
